// This file is generated by the create_littleFS_image.py script
// It contains the address of each binary file in the littleFS image
// Do not edit this file manually
#ifndef ADDRESS_BINARY_FILES_H
#define ADDRESS_BINARY_FILES_H
#define CHART_MIN_START_ADDRESS 0x106000
#define CHART_MIN_END_ADDRESS 0x10600e
#endif // ADDRESS_BINARY_FILES_H
