name=littleFS
version=1.0
author=Nicolae Hagiu
maintainer=Nicolae Hagiu
sentence=This Library is used to create files in the flash memory of the ESP8266 using the littleFS file system.
paragraph= This Library is used to create files in the flash memory of the ESP8266 using the littleFS file system. It provides functions to create, read, write and delete files in the flash memory of the ESP8266. It also provides functions to get the list of files in the flash memory of the ESP8266 and to get the size of a file in the flash memory of the ESP8266.
category=Interface
url=https://github.com/hagiu10/Scale_ESP8266
architectures=*