from glob import glob
from pathlib import Path
import subprocess
import serial.tools.list_ports as serial
from cli.tools.create_littlleFS_image import create_binary_files, create_littleFS_image
from cli.tools.get_com_port_ESP8266 import get_com_port_ESP8266


def flash_littleFS_cmd():
    """ Flash the littleFS image onto the ESP8266."""
    # Get root directory of the project
    ROOT = Path(__file__).parent.parent.parent.resolve()
    # Path to the esptool.py executable

    matches = glob(str(ROOT / "workspace/arduino/packages/esp8266/hardware/esp8266/*/tools/esptool/esptool.py"))

    if not matches:
        raise RuntimeError("esptool.py not found in the expected directory.")

    path_esp_tool_py = Path(matches[-1])

    # Path to the binary files created from the data directory
    path_binary_dir = ROOT/ "bin" / "littleFS"
    
    create_header_file() # Create the address binary header file before flashing the binary files
    #create_littleFS_image() # Create the littleFS image before flashing it
    create_binary_files() # Create binary files from the data directory before flashing them

    com_port = get_com_port_ESP8266()

    # Write each binary file to the flash memory of the ESP8266 start at 0x300000
    start_address = 0x106000
    max_address = 0x400000

    for binary_file in path_binary_dir.glob("*.bin"):
        if start_address > max_address:
            print("Error: Not enough flash memory to write all binary files.")
            break

        size = binary_file.stat().st_size
        end_address = start_address + size

        if end_address > max_address:
            print(f"Error: Not enough flash memory to write {binary_file.name}.")
            break

        print(f"Flashing {binary_file} between address {hex(start_address)} and {hex(end_address)}")

        command = ["python", str(path_esp_tool_py),
                    "--port", com_port,
                    "--baud", "115200",
                    "write_flash", hex(start_address), str(binary_file)
                    ]

        result = subprocess.run(command, shell=True, 
                                stdout = subprocess.PIPE,
                                text=True,
                                check=True, 
                                encoding="utf-8",
                                errors="replace")
        print(f"\nStdout:\n{result.stdout}")
        success_string = "Hash of data verified."
        if  success_string in result.stdout:
            print("Flashing binary files successful!")
            write_address_binary_header(binary_file.stem, start_address, end_address) # Write the address of the binary file to the address binary header file
        else:
            print("Flashing binary files failed!")
            print(result.stderr)
        start_address = start_address + size

    add_last_line_address_binary_header() # Add the last line to the address binary header file

def create_header_file():
    """ Create the address binary header file for the littleFS image."""
    # Get root directory of the project
    ROOT = Path(__file__).parent.parent.parent.resolve()
    # Path to the address binary header file
    path_address_binary_header = ROOT / "arduino" / "libraries" / "littleFS" / "src"/ "address_binary_files.h"
    # Clear the content of the address binary header file
    with open(path_address_binary_header, "w") as f:
        f.write("// This file is generated by the create_littleFS_image.py script\n")
        f.write("// It contains the address of each binary file in the littleFS image\n")
        f.write("// Do not edit this file manually\n")
        f.write("#ifndef ADDRESS_BINARY_FILES_H\n")
        f.write("#define ADDRESS_BINARY_FILES_H\n")

def write_address_binary_header(file_name, start_address, end_address):
    """ Write the address of a binary file to the address binary header file."""
    # Get root directory of the project
    ROOT = Path(__file__).parent.parent.parent.resolve()
    # Path to the address binary header file
    path_address_binary_header = ROOT / "arduino" / "libraries" / "littleFS" / "src"/ "address_binary_files.h"
    # Write the address of the binary file to the address binary header file
    with open(path_address_binary_header, "a") as f:
        f.write(f"#define {file_name.upper()}_START_ADDRESS {hex(start_address)}\n")
        f.write(f"#define {file_name.upper()}_END_ADDRESS {hex(end_address)}\n")

def add_last_line_address_binary_header():
    """ Add the last line to the address binary header file."""
    # Get root directory of the project
    ROOT = Path(__file__).parent.parent.parent.resolve()
    # Path to the address binary header file
    path_address_binary_header = ROOT / "arduino" / "libraries" / "littleFS" / "src"/ "address_binary_files.h"
    # Add the last line to the address binary header file
    with open(path_address_binary_header, "a") as f:
        f.write("#endif // ADDRESS_BINARY_FILES_H\n")